import { dmSans, lato } from '@/assets/fonts/Fonts'
import { Footer } from '@/components/layout/footer/Footer'
import { Header } from '@/components/layout/header/Header'
import '@/styles/style.css'
import type { Metadata } from 'next'
import 'swiper/css'
import 'swiper/css/grid'
import 'swiper/css/pagination'

export const metadata: Metadata = {
	title: 'Get My Car',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' className={`${lato.className} ${dmSans.className}`}>
			<body>
				<div className='wrapper'>
					<Header />
					<main>{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	)
}
