import { dmSans, lato } from '@/assets/fonts/Fonts'
import { Footer } from '@/components/layout/footer/Footer'
import '@/styles/style.css'
import type { Metadata } from 'next'
dmSans
lato

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body>
				<div className='wrapper'>
					<main>{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	)
}
